services:
  postgres:
    image: postgres
    container_name: vajilla-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: vajilla
    ports:
      - "5542:5432"
    volumes:
      - vajilla_data:/var/lib/postgresql/data
  app:
    build:
      context: .
    container_name: vajilla-app
    ports:
      - "5001:5001"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:root@postgres:5432/vajilla
volumes:
  vajilla_data:
