INSERT INTO products (name, brand, price, img) VALUES
('Tenedor', 'Paris', 180, './assets/tenedorParis.png'),
('Cuchara de postre', 'Paris', 160, './assets/cucharaPostre.png'),
('Mantel blanco 1.75mts 2mts 3mts', '', 3000, './assets/mantel.png'),
('Servilletero', '', 350, './assets/servilletero.png'),
('Bandeja de mozo', '', 900, './assets/bandejamozo.png'),
('Plato Principal', 'Olmos', 350, './assets/platoOlmos.png'),
('Cubre manteles 75x75', '', 850, './assets/manteles.png'),
('Hielera con pinza', '', 700, './assets/hielera.png'),
('Panera', '', 450, './assets/panera.png'),
('Cazuelita', '', 320, './assets/cazuelita.png'),
('Cenicero', '', 320, './assets/cenicero.png'),
('Bandeja de asado', '', 900, './assets/fuente.png'),
('Plato de postre', 'Olmos', 250, './assets/platopostre.png'),
('Cuchillo', 'Paris', 180, './assets/cuchilloParis.png'),
('Jarra de vidrio', '', 600, './assets/jarraVidrio.png'),
('Copa de agua', '', 200, './assets/copaAgua.png'),
('Copa flauta', '', 250, './assets/copaChampagne.png'),
('Salero', '', 350, './assets/salero.png');
